In [1]:
from scipy.io import loadmat
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib widget

In [3]:
# mat = loadmat('EPOT_255_250.mat')
Ex_Validation = 'Experimental_validation'

In [5]:
rootdir = os.getcwd()
os.chdir(rootdir)

In [16]:
# Initialize lists for training and validation
ex_val_data = []; ex_val_labels = []

#------------------------------------------------------------------------------

for subdir, dirs, files in os.walk(rootdir):
    
    if Ex_Validation.lower() in subdir.lower():
        for file in files:
            if file.endswith('.txt'):
                
                with open(os.path.join(subdir, file), 'r') as f:
                    # print(file.split('_')[2], file.split('_')[3], file.split('_')[5][:3])
                    lbl = [file.split('_')[2], file.split('_')[3], file.split('_')[5][:3]]
                    lb = np.asarray(lbl, dtype=float)

                    x = pd.read_csv(os.path.join(subdir, file), delimiter='\t', decimal=',', skiprows=8, header=None)
                    x = np.asarray(x, dtype=float)
                    ex_val_data.append(x)
                    ex_val_labels.append(lb)

In [17]:
ex_val_labels

[array([205., 200.,   1.]),
 array([205., 200.,   2.]),
 array([205., 200.,   3.]),
 array([205., 200.,   4.]),
 array([225., 210.,   1.]),
 array([225., 210.,   2.]),
 array([225., 210.,   3.]),
 array([225., 210.,   4.]),
 array([230., 245.,   1.]),
 array([230., 245.,   2.]),
 array([230., 245.,   3.]),
 array([230., 245.,   4.]),
 array([240., 255.,   1.]),
 array([240., 255.,   2.]),
 array([240., 255.,   3.]),
 array([240., 255.,   4.]),
 array([250., 260.,   1.]),
 array([250., 260.,   2.]),
 array([250., 260.,   3.]),
 array([250., 260.,   4.]),
 array([300., 235.,   1.]),
 array([300., 235.,   2.]),
 array([300., 235.,   3.]),
 array([300., 235.,   4.])]